services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=airflow
    volumes:
      - ./database/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d db -U airflow || exit 1"]
      interval: 15s
      retries: 5
    ports:
      - "5433:5432"
    restart: always

  scheduler:
    build: .
    command: poetry run airflow scheduler
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "poetry run airflow jobs check --job-type SchedulerJob --local || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:$POSTGRES_PASSWORD@postgres:5432/db
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      #set the dbt directory
      - DBT_DIR=/app/airflow/dbt_linkedin_etl_project
      - SNOWFLAKE_USER=$SNOWFLAKE_USER
      - SNOWFLAKE_PASSWORD=$SNOWFLAKE_PASSWORD
      - SNOWFLAKE_ACCOUNT=$SNOWFLAKE_ACCOUNT
      - SNOWFLAKE_WAREHOUSE=SNOWFLAKE_LEARNING_WH
      - SNOWFLAKE_DATABASE=linkedin_db
      - SNOWFLAKE_SCHEMA=linkedin_raw
    volumes:
      - ./dags:/app/airflow/dags
      - ./data:/app/airflow/data
      - ./logs:/app/airflow/logs
      #added dbt volumes
      - ./dbt_linkedin_etl_project:/app/airflow/dbt_linkedin_etl_project



  webserver:
    build: .
    command: poetry run scripts/entrypoint.sh
    restart: on-failure
    depends_on:
      - postgres
      - scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:$POSTGRES_PASSWORD@postgres:5432/db
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=airflow
      #set the dbt directory
      - DBT_DIR=/app/airflow/dbt_linkedin_etl_project
    volumes:
      - ./dags:/app/airflow/dags
      - ./data:/app/airflow/data
      - ./logs:/app/airflow/logs
      #added dbt volumes
      - ./dbt_linkedin_etl_project:/app/airflow/dbt_linkedin_etl_project

    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
