services:
  postgres_airflow:
    image: postgres:14
    environment:
      - POSTGRES_DB=airflow_db
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=$AIRFLOW_DB_PASSWORD
    volumes:
      - ./database/airflow:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d airflow_db -U airflow || exit 1"]
      interval: 30s
      retries: 5
      start_period: 60s
    ports:
      - "5433:5432"
    restart: always

  postgres_warehouse:
    image: postgres:14
    environment:
      - POSTGRES_DB=warehouse_db
      - POSTGRES_USER=warehouse_user
      - POSTGRES_PASSWORD=$WAREHOUSE_PASSWORD
    volumes:
      - ./database/warehouse:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d warehouse_db -U warehouse_user || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  scheduler:
    build: .
    command: bash -c "poetry run airflow db upgrade && poetry run airflow scheduler"
    restart: on-failure
    depends_on:
      - postgres_airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:$AIRFLOW_DB_PASSWORD@postgres_airflow:5432/airflow_db
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
    volumes:
      - ./dags:/app/airflow/dags
      - ./data:/app/airflow/data
      - ./logs:/app/airflow/logs
    healthcheck:
      test: ["CMD-SHELL", "poetry run airflow jobs check --job-type SchedulerJob --local || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  webserver:
    build: .
    command: poetry run scripts/entrypoint.sh
    restart: on-failure
    depends_on:
      - postgres_airflow
      - postgres_warehouse
      - scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      # Airflow uses this metadata DB connection and creates it's own metadata assets from this connection string
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:$AIRFLOW_DB_PASSWORD@postgres_airflow:5432/airflow_db
      # Required for 'init_connections.sh' to create the warehouse DB connection
      - WAREHOUSE_DB=warehouse_db
      - WAREHOUSE_USER=warehouse_user
      - WAREHOUSE_PASSWORD=$WAREHOUSE_PASSWORD
    volumes:
      - ./dags:/app/airflow/dags
      - ./data:/app/airflow/data
      - ./logs:/app/airflow/logs
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 60s
